[profile]
    flag="dev-local"
[mongo]
    hostUri="mongodb://localhost:27017"
    name="nbaPickAndPlay"
[rapid]
    enabled=true
    season="2019"
    baseUrl="http://localhost:8081/games/date/"
    apiKey="nope"